{\rtf1\ansi\ansicpg1252\cocoartf2759
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 create table public.settings (\
  id bigint generated by default as identity not null,\
  created_at timestamp with time zone not null default now(),\
  "songCount" smallint null,\
  "sermonCount" smallint null,\
  intro_verse1 text not null default 'Come, let us sing for joy to the Lord; let us shout aloud to the Rock of our salvation. Let us come before him with thanksgiving and extol him with music and song. (Psalm 95:1-2)'::text,\
  intro_verse2 text not null default 'Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom, singing psalms and hymns and spiritual songs, with thankfulness in your hearts to God. (Colossians 3:16)''::text'::text,\
  "newSongs" boolean null default false,\
  livestream_url text null,\
  constraint settings_pkey primary key (id)\
) TABLESPACE pg_default;}