create table public."songsList" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "songTitle" text not null,
  "lyricsUrl" text null default ''::text,
  "copyRight" text not null default ''::text,
  youtube_url text null default 'emptyUrl'::text,
  new_song boolean not null default false,
  songfortheday_played boolean not null default false,
  "startAt" smallint null,
  "endAt" smallint null,
  constraint songsList_pkey primary key ("songTitle"),
  constraint songsList_songTitle_key unique ("songTitle")
) TABLESPACE pg_default;

create index IF not exists "songsList_new_song_idx" on public."songsList" using btree (new_song) TABLESPACE pg_default;