{\rtf1\ansi\ansicpg1252\cocoartf2759
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 create table public."topicSeries" (\
  id bigint generated by default as identity not null,\
  created_at timestamp with time zone not null default now(),\
  "seriesTitle" text not null,\
  current boolean null default false,\
  sequence smallint null,\
  "seriesGraphic" text null,\
  "SeriesTag" text null,\
  "fromDate" text null default ''::text,\
  "toDate" text null default ''::text,\
  constraint topicSeries_pkey primary key (id, "seriesTitle")\
) TABLESPACE pg_default;}